root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/mimux ./cmd/mimux"
bin = "./tmp/mimux"
include_ext = ["go", "html", "css", "js", "toml", "sql", "json"]
exclude_dir = ["tmp", "bin", "data", "node_modules", ".git"]
exclude_regex = ["dist\\.css$"]

[misc]
clean_on_exit = true
