// SPDX-License-Identifier: AGPL-3.0-only
package mail

import (
	"regexp"
	"strings"
)

// attachWords are the (English + Italian) stems that suggest the writer meant
// to attach a file. Matched as whole words, case-insensitively. Kept in sync
// with the same list mirrored in web/static/js/app.js (attachKeywords).
var attachWords = []string{
	"attach", "attached", "attachment", "attachments", "attaching",
	"enclosed",
	"allegato", "allegati", "allegata", "allegate", "allego",
}

// attachRe matches any attachWords entry as a whole word (word boundaries so
// "attach" won't fire inside "attaches"—actually it will via the stem; the
// boundary just avoids matching inside unrelated longer tokens like "detach").
var attachRe = func() *regexp.Regexp {
	quoted := make([]string, len(attachWords))
	for i, w := range attachWords {
		quoted[i] = regexp.QuoteMeta(w)
	}
	return regexp.MustCompile(`(?i)\b(` + strings.Join(quoted, "|") + `)\b`)
}()

var (
	htmlQuoteStartRe    = regexp.MustCompile(`(?is)<blockquote\b`)
	replyQuoteStartRe   = regexp.MustCompile(`(?im)^[ \t]*On .+ wrote:[ \t]*\r?\n(?:[ \t]*\r?\n)*[ \t]*>`)
	forwardQuoteStartRe = regexp.MustCompile(`(?im)^[ \t]*---------- Forwarded message ----------[ \t]*(?:\r?\n|$)`)
	quotedLineRe        = regexp.MustCompile(`^[ \t]*>`)
)

// MentionsAttachment reports whether text authored in a compose hints at an
// attachment ("please find attached", "in allegato", …). It excludes quoted
// reply and forward text so a sender is not warned about an attachment that
// only the original message mentioned.
func MentionsAttachment(text string) bool {
	return attachRe.MatchString(stripQuotedText(text))
}

// stripQuotedText removes the quote formats generated by the compose editor.
// An attribution counts as a quote only when it is followed by a >-prefixed
// line, so prose such as "On Monday, I wrote:" remains the sender's text.
func stripQuotedText(text string) string {
	if match := htmlQuoteStartRe.FindStringIndex(text); match != nil {
		text = text[:match[0]]
	}
	if match := forwardQuoteStartRe.FindStringIndex(text); match != nil {
		text = text[:match[0]]
	}
	if match := replyQuoteStartRe.FindStringIndex(text); match != nil {
		text = text[:match[0]]
	}

	lines := strings.Split(text, "\n")
	kept := lines[:0]
	for _, line := range lines {
		if !quotedLineRe.MatchString(line) {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}
