package translate

import "slices"

// Language is one entry of Google Translate's supported-language list.
type Language struct {
	Code string
	Name string
}

// Languages are the languages Google Translate accepts as a source or target,
// already sorted by English name so a template can range over them straight
// into a <select>.
//
// ponytail: static snapshot, not a call to the API's /languages endpoint —
// that needs the API key, adds a failure path and a cache of its own, and the
// list grows maybe once a year. Refresh by hand from
// https://cloud.google.com/translate/docs/languages
var Languages = []Language{
	{"af", "Afrikaans"},
	{"sq", "Albanian"},
	{"am", "Amharic"},
	{"ar", "Arabic"},
	{"hy", "Armenian"},
	{"as", "Assamese"},
	{"ay", "Aymara"},
	{"az", "Azerbaijani"},
	{"bm", "Bambara"},
	{"eu", "Basque"},
	{"be", "Belarusian"},
	{"bn", "Bengali"},
	{"bho", "Bhojpuri"},
	{"bs", "Bosnian"},
	{"bg", "Bulgarian"},
	{"ca", "Catalan"},
	{"ceb", "Cebuano"},
	{"zh-CN", "Chinese (Simplified)"},
	{"zh-TW", "Chinese (Traditional)"},
	{"co", "Corsican"},
	{"hr", "Croatian"},
	{"cs", "Czech"},
	{"da", "Danish"},
	{"dv", "Divehi"},
	{"doi", "Dogri"},
	{"nl", "Dutch"},
	{"en", "English"},
	{"eo", "Esperanto"},
	{"et", "Estonian"},
	{"ee", "Ewe"},
	{"tl", "Filipino (Tagalog)"},
	{"fi", "Finnish"},
	{"fr", "French"},
	{"fy", "Frisian"},
	{"gl", "Galician"},
	{"ka", "Georgian"},
	{"de", "German"},
	{"el", "Greek"},
	{"gn", "Guarani"},
	{"gu", "Gujarati"},
	{"ht", "Haitian Creole"},
	{"ha", "Hausa"},
	{"haw", "Hawaiian"},
	{"he", "Hebrew"},
	{"hi", "Hindi"},
	{"hmn", "Hmong"},
	{"hu", "Hungarian"},
	{"is", "Icelandic"},
	{"ig", "Igbo"},
	{"ilo", "Ilocano"},
	{"id", "Indonesian"},
	{"ga", "Irish"},
	{"it", "Italian"},
	{"ja", "Japanese"},
	{"jv", "Javanese"},
	{"kn", "Kannada"},
	{"kk", "Kazakh"},
	{"km", "Khmer"},
	{"rw", "Kinyarwanda"},
	{"gom", "Konkani"},
	{"ko", "Korean"},
	{"kri", "Krio"},
	{"ku", "Kurdish"},
	{"ckb", "Kurdish (Sorani)"},
	{"ky", "Kyrgyz"},
	{"lo", "Lao"},
	{"la", "Latin"},
	{"lv", "Latvian"},
	{"ln", "Lingala"},
	{"lt", "Lithuanian"},
	{"lg", "Luganda"},
	{"lb", "Luxembourgish"},
	{"mk", "Macedonian"},
	{"mai", "Maithili"},
	{"mg", "Malagasy"},
	{"ms", "Malay"},
	{"ml", "Malayalam"},
	{"mt", "Maltese"},
	{"mi", "Maori"},
	{"mr", "Marathi"},
	{"mni-Mtei", "Meiteilon (Manipuri)"},
	{"lus", "Mizo"},
	{"mn", "Mongolian"},
	{"my", "Myanmar (Burmese)"},
	{"ne", "Nepali"},
	{"no", "Norwegian"},
	{"ny", "Nyanja (Chichewa)"},
	{"or", "Odia (Oriya)"},
	{"om", "Oromo"},
	{"ps", "Pashto"},
	{"fa", "Persian"},
	{"pl", "Polish"},
	{"pt", "Portuguese"},
	{"pa", "Punjabi"},
	{"qu", "Quechua"},
	{"ro", "Romanian"},
	{"ru", "Russian"},
	{"sm", "Samoan"},
	{"sa", "Sanskrit"},
	{"gd", "Scots Gaelic"},
	{"nso", "Sepedi"},
	{"sr", "Serbian"},
	{"st", "Sesotho"},
	{"sn", "Shona"},
	{"sd", "Sindhi"},
	{"si", "Sinhala"},
	{"sk", "Slovak"},
	{"sl", "Slovenian"},
	{"so", "Somali"},
	{"es", "Spanish"},
	{"su", "Sundanese"},
	{"sw", "Swahili"},
	{"sv", "Swedish"},
	{"tg", "Tajik"},
	{"ta", "Tamil"},
	{"tt", "Tatar"},
	{"te", "Telugu"},
	{"th", "Thai"},
	{"ti", "Tigrinya"},
	{"ts", "Tsonga"},
	{"tr", "Turkish"},
	{"tk", "Turkmen"},
	{"ak", "Twi (Akan)"},
	{"uk", "Ukrainian"},
	{"ur", "Urdu"},
	{"ug", "Uyghur"},
	{"uz", "Uzbek"},
	{"vi", "Vietnamese"},
	{"cy", "Welsh"},
	{"xh", "Xhosa"},
	{"yi", "Yiddish"},
	{"yo", "Yoruba"},
	{"zu", "Zulu"},
}

// Supported reports whether code is on the list above. Codes arrive from the
// query string and end up in an outbound API request, so callers reject
// anything that isn't a known language instead of forwarding it. The empty
// string (auto-detect) is not a language and is not supported.
func Supported(code string) bool {
	return slices.ContainsFunc(Languages, func(l Language) bool { return l.Code == code })
}
