// SPDX-License-Identifier: AGPL-3.0-only

package main

// `mimux completion <bash|zsh>` — a shell completion script, generated at
// print time from the same subcommands map (and, in a pro build, the mail
// verb table) the dispatcher itself consults. Free-side like upgrade: no
// build tag, so both binaries carry the command, and each one's script
// matches what it actually implements — a free binary never offers to
// complete `mail`, `mcp` or `licence`, because it does not have them.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

func init() {
	subcommands["completion"] = runCompletion
}

// mailVerbs lists `mimux mail`'s verbs, for the second level of completion.
// Empty in the free build. The pro-tagged cli.go fills it from pro.CLIVerbs()
// in its own init(), the same registration-hook pattern main.go's doc comment
// describes for subcommands itself — cmd/mimux must not import pro/ directly.
var mailVerbs []string

// mailSubverbs is the third level: a `mimux mail` verb that nests, mapped to
// its own subcommands. Same registration hook as mailVerbs, and empty in the
// free build for the same reason. `mimux mail webhooks <TAB>` is the only one
// today.
var mailSubverbs map[string][]string

// sortedSubverbs keeps the generated script stable across runs — a map range
// would reorder it, and a completion script that changes for no reason is a
// diff nobody can review.
func sortedSubverbs() []string {
	verbs := make([]string, 0, len(mailSubverbs))
	for v := range mailSubverbs {
		verbs = append(verbs, v)
	}
	sort.Strings(verbs)
	return verbs
}

func runCompletion(args []string) int {
	if len(args) == 1 {
		switch args[0] {
		case "bash":
			fmt.Print(bashCompletion())
			return 0
		case "zsh":
			fmt.Print(zshCompletion())
			return 0
		}
	}
	completionUsage(os.Stderr)
	return 2
}

// topLevelWords is every word `mimux <TAB>` should offer: the registered
// verbs plus the one flag main.go handles itself before ever consulting the
// subcommands map.
func topLevelWords() []string {
	words := make([]string, 0, len(subcommands)+1)
	for name := range subcommands {
		words = append(words, name)
	}
	sort.Strings(words)
	return append(words, "-version")
}

func completionUsage(w io.Writer) {
	_, _ = fmt.Fprint(w, `usage: mimux completion <bash|zsh>

Prints a shell completion script to stdout.

bash, system-wide (root):
  mimux completion bash | sudo tee /etc/bash_completion.d/mimux >/dev/null

bash, this user only:
  mkdir -p ~/.local/share/bash-completion/completions
  mimux completion bash > ~/.local/share/bash-completion/completions/mimux
  # bash-completion picks this up automatically; otherwise add to ~/.bashrc:
  #   source ~/.local/share/bash-completion/completions/mimux

zsh, any directory on $fpath:
  mkdir -p ~/.zsh/completions && fpath+=(~/.zsh/completions)  # in ~/.zshrc, before compinit
  mimux completion zsh > ~/.zsh/completions/_mimux
  autoload -Uz compinit && compinit
`)
}

func bashCompletion() string {
	var b strings.Builder
	b.WriteString("# mimux bash completion — generated by `mimux completion bash`\n")
	fmt.Fprintf(&b, "_mimux() {\n  local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(&b, "  if [ \"$COMP_CWORD\" -eq 1 ]; then\n    COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n    return\n  fi\n",
		strings.Join(topLevelWords(), " "))
	if len(mailVerbs) > 0 {
		fmt.Fprintf(&b, "  if [ \"${COMP_WORDS[1]}\" = mail ] && [ \"$COMP_CWORD\" -eq 2 ]; then\n    COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n  fi\n",
			strings.Join(mailVerbs, " "))
		for _, verb := range sortedSubverbs() {
			fmt.Fprintf(&b, "  if [ \"${COMP_WORDS[1]}\" = mail ] && [ \"${COMP_WORDS[2]}\" = %s ] && [ \"$COMP_CWORD\" -eq 3 ]; then\n    COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n  fi\n",
				verb, strings.Join(mailSubverbs[verb], " "))
		}
	}
	b.WriteString("}\ncomplete -F _mimux mimux\n")
	return b.String()
}

func zshCompletion() string {
	var b strings.Builder
	b.WriteString("#compdef mimux\n# mimux zsh completion — generated by `mimux completion zsh`\n\n_mimux() {\n")
	fmt.Fprintf(&b, "  local -a cmds; cmds=(%s)\n", strings.Join(topLevelWords(), " "))
	b.WriteString("  if (( CURRENT == 2 )); then\n    _describe 'command' cmds\n    return\n  fi\n")
	if len(mailVerbs) > 0 {
		fmt.Fprintf(&b, "  local -a mail_verbs; mail_verbs=(%s)\n", strings.Join(mailVerbs, " "))
		b.WriteString("  if [[ \"${words[2]}\" == mail && \"$CURRENT\" == 3 ]]; then\n    _describe 'mail command' mail_verbs\n    return\n  fi\n")
		for _, verb := range sortedSubverbs() {
			fmt.Fprintf(&b, "  local -a %s_subverbs; %s_subverbs=(%s)\n", verb, verb, strings.Join(mailSubverbs[verb], " "))
			fmt.Fprintf(&b, "  if [[ \"${words[2]}\" == mail && \"${words[3]}\" == %s && \"$CURRENT\" == 4 ]]; then\n    _describe '%s command' %s_subverbs\n    return\n  fi\n",
				verb, verb, verb)
		}
	}
	b.WriteString("}\n\n_mimux \"$@\"\n")
	return b.String()
}
